### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method ‘java.lang.String java.io.File.getAbsolutePath()’ on a null object reference

### ISSUE THREAD

**Issue by alijohar** [Angads25/android-filepicker#56]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method ‘java.lang.String java.io.File.getAbsolutePath()’ on a null object reference
       at com.github.angads25.filepicker.view.FilePickerDialog.onItemClick(SourceFile:213)
       at android.widget.AdapterView.performItemClick(AdapterView.java:334)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3664)
       at android.widget.AbsListView$3.run(AbsListView.java:5585)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by singhangadin** [comment]
Hey, which version of library are you using in your app?

**Comment by alijohar** [comment]
1.0.8

**Comment by GiorgiToNieve** [comment]
Pudieron solucionarlo?

**Comment by esunilkumare** [comment]
Hi Angad,

Facing this same issue on filepicker:1.1.1 version as well.  Do we have any solutions for this issue?
Please note this is happening when we press back button without selecting any documents.

--
Thanks
Sunil
